# Generated by Django 6.0.4 on 2026-05-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_alter_category_options_alter_topping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_cream', to='ice_cream.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='toppings',
            field=models.ManyToManyField(related_name='ice_cream', to='ice_cream.topping', verbose_name='Топпинги'),
        ),
    ]
